site_name: CSAF
site_description: Yes, another such thing.

theme:
  name: 'material'
  logo: assets/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.expand
    - toc.integrate
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false
  homepage: https://codes.dilettant.life/docs/
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/csaf
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shage

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2023 Stefan Hagen under the MIT license

repo_name: sthagen/csaf
repo_url: https://git.sr.ht/~sthagen/csaf
edit_uri: ""

plugins:
  - search
  - mkdocstrings

nav:
  - Introduction: 'index.md'
  - Quickstart: 'quick.md'
  - Install: 'install.md'
  - Usage: 'usage.md'
  - API: 'api.md'
  - CLI: 'cli.md'
  - Background: 'background.md'
  - Changes: 'changes.md'
  - Test Coverage: https://codes.dilettant.life/coverage/csaf
  - Third-Party: 'third-party/README.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: '∞'
  - mkautodoc
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:

